services:
  franka_dev:
    image: wngfra/ros2cuda:base
    ports:
        - 8888:8888
    volumes:
      - ../fingerSense:/workspace/fingerSense
    container_name: pytorch-notebook-container
    runtime: nvidia    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
